### ISSUE TITLE
Configuration export/import issue

### ISSUE THREAD

**Issue by raymondpancura** [Vardot/varbase_auth#2]
varbase_auth.install creates a settings file called simple.settings  When you export config this creates a simple.settings.yml file in the sync folder.  If you attempt to import config into another site you get an error, <em>"Configuration simple.settings depends on the simple extension that will not be installed after import."</em>

Can you name this properly so that it does not think it requires the simple extension (varbase_auth.settings)?

**Comment by fercamp** [comment]
Hi, I have the same problem. and was able to verify the following lines in varbase_auth/varbase_auth.install
```
   22:   $configFactory = \Drupal::configFactory()->getEditable('simple.settings');
   23    $auth_modules = $configFactory->get('social_auth_type');
```
Is there a solution so I can import single configs into other site?

**Comment by raymondpancura** [comment]
fercamp, just rename the simple.settings.yml to varbase_auth.settings.yml
